# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   annotations:
#     volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/aws-ebs
#   labels:
#     app: jenkins
#   name: jenkins-data-pv-claim
#   namespace: jenkins
# spec:
#   storageClassName: gp2
#   accessModes:
#     - ReadWriteOnce
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: "example-nfs"
  labels:
    app: jenkins
  name: jenkins-data-pv-claim
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
