#global:
#  hosts:
#    domain: example.com
#    externalIP: 10.0.0.0
##  ingress:
##    configureCertmanager: false
##    class: "nginx"
##  hosts:
##    domain: 192.168.99.100.nip.io
##    externalIP: 192.168.99.100
#  # Disable Rails bootsnap cache (temporary)
##  rails:
##    bootsnap:
##      enabled: false
## Don't use certmanager, we'll self-sign
##certmanager:
##  install: false
## Use the `ingress` addon, not our Ingress (can't map 22/80/443)
##nginx-ingress:
##  enabled: false
## Save resources, only 2 CPU
#prometheus:
#  install: false
## GitLab Runner isn't a big fan of self-signed certificates
#gitlab-runner:
#  install: false
## Reduce replica counts, reducing CPU & memory requirements
#gitlab:
#  unicorn:
#    minReplicas: 1
#    maxReplicas: 1
#  sidekiq:
#    minReplicas: 1
#    maxReplicas: 1
#  gitlab-shell:
#    minReplicas: 1
#    maxReplicas: 1
#registry:
#  hpa:
#    minReplicas: 1
#    maxReplicas: 1

global:
  ingress:
    configureCertmanager: true
    class: "nginx"
  hosts:
    domain: example.com
    externalIP: 10.0.0.0
# Don't use certmanager, we'll self-sign
certmanager:
  install: true
# Use the `ingress` addon, not our Ingress (can't map 22/80/443)
nginx-ingress:
  enabled: true
prometheus:
  install: false
# GitLab Runner isn't a big fan of self-signed certificates
gitlab-runner:
  install: false

