apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: redis
    release: gitlab
    role: master
  name: redis-data-gitlab-redis-master-0
  namespace: testgit
  resourceVersion: "165325"
  selfLink: /api/v1/namespaces/testgit/persistentvolumeclaims/redis-data-gitlab-redis-master-0
  uid: 93d4a89e-7c09-4d01-b49a-16b6659796b4
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: example-nfs
  volumeMode: Filesystem